 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdrailway;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javafx.scene.paint.Color;
import bdrailway.Login;
import javax.swing.JOptionPane;

public class TrainTicketingSystem extends javax.swing.JFrame {

    /**
     * Creates new form TrainTicketingSystem
     */
    public TrainTicketingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 8));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Gender :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Adult ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Child");

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Class :");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Standard");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Economy");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton3.setText("Shovon Chair");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setText("Male");

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setText("Female");

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton7.setText("Yes");

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton8.setText("Yes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Destination");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select area", "Chittagong", "Rajshahi", "Khulna", "Syllhet", "Dinajpur", "Rangpur" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton2)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton8))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton7)
                        .addComponent(jRadioButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("      Train Ticketing System");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sub Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Total");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 51));
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Exit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField3.setBackground(new java.awt.Color(204, 255, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(89, 89, 89)
                                .addComponent(jButton3))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Name :");

        jTextField4.setBackground(new java.awt.Color(255, 204, 204));
        jTextField4.setForeground(new java.awt.Color(153, 153, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("From  :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("To       :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Date   :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Time   :");

        jTextField5.setBackground(new java.awt.Color(255, 204, 204));
        jTextField5.setForeground(new java.awt.Color(0, 51, 255));

        jTextField6.setBackground(new java.awt.Color(255, 204, 204));
        jTextField6.setForeground(new java.awt.Color(153, 0, 0));

        jTextField7.setBackground(new java.awt.Color(255, 204, 204));
        jTextField7.setForeground(new java.awt.Color(0, 0, 102));

        jTextField8.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("TicketNo");

        jTextField9.setBackground(new java.awt.Color(255, 204, 204));

        jTextField10.setBackground(new java.awt.Color(255, 204, 204));
        jTextField10.setForeground(new java.awt.Color(102, 102, 102));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Price   :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(40, 40, 40)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //Calendar;
        Calendar timer =Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new  SimpleDateFormat("HH:mm:ss");
        
        //Time;
        jTextField9.setText(tTime.format(timer.getTime()));
        SimpleDateFormat tdate = new SimpleDateFormat("dd-MMM-yyyy");
        jTextField8.setText(tdate.format(timer.getTime()));
        
        //Your Location;
        jTextField6.setText("Dhaka");
        
        //Ticket number;
        int num1;
        String q1 = "";
        num1 = (int)(200+Math.random()*(500-200+1));
        q1 += num1;
        
        jTextField4.setText(q1);
        
        
        
         //take location from comboBox;      
        String To =  (String)jComboBox2.getSelectedItem();
        jTextField7.setText(To);
        jTextField5.setText("abir");
        
        //Total coast;
        //Standard_Male_Adult_Chittagong;
        if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("796.48 tk");
            jTextField10.setText("796.48 tk only");
            
        }
        
        //Standard_Male_Child_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Standard_Female_Adult_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("796.48 tk");
            jTextField10.setText("796.48 tk only");
            
        }
        
         //Standard_Female_Child_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
         //Economy_Male_Adult_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("559 tk");
            jTextField2.setText("5%");
            jTextField3.setText("586.95 tk");
            jTextField10.setText("586.95 tk only");
            
        }
        
        //Economy_Male_Child_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Economy_Female_Adult_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("559 tk");
            jTextField2.setText("5%");
            jTextField3.setText("586.95 tk");
            jTextField10.setText("586.95 tk only");
            
        }
        
         //Economy_Female_Child_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("900 tk");
            jTextField2.setText("5%");
            jTextField3.setText("945 tk");
            jTextField10.setText("945 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("900 tk");
            jTextField2.setText("5%");
            jTextField3.setText("945 tk");
            jTextField10.setText("945 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("800 tk");
            jTextField2.setText("5%");
            jTextField3.setText("840 tk");
            jTextField10.setText("840 tk only");
            
        }
        
        //Standard_Male_Child_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("650 tk");
            jTextField2.setText("5%");
            jTextField3.setText("682.5 tk");
            jTextField10.setText("682.5 tk only");
            
        }
        
        //Standard_Female_Adult_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("800 tk");
            jTextField2.setText("5%");
            jTextField3.setText("840 tk");
            jTextField10.setText("840 tk only");
            
        }
        
         //Standard_Female_Child_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("650 tk");
            jTextField2.setText("5%");
            jTextField3.setText("682.5 tk");
            jTextField10.setText("682.5 tk only");
            
        }
        
         //Economy_Male_Adult_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Economy_Male_Child_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("367.5 tk only");
            
        }
        
        //Economy_Female_Adult_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
         //Economy_Female_Child_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("367.5 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Khulna;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("500 tk");
            jTextField2.setText("5%");
            jTextField3.setText("525 tk");
            jTextField10.setText("840 tk only");
            
        }
        
        //Standard_Male_Child_Khulna;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("682.5 tk only");
            
        }
        
        //Standard_Female_Adult_Khulna;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("500 tk");
            jTextField2.setText("5%");
            jTextField3.setText("525 tk");
            jTextField10.setText("525 tk only");
            
        }
        
         //Standard_Female_Child_Khulna;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("367.5 tk only");
            
        }
        
         //Economy_Male_Adult_Khulna;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Economy_Male_Child_Khulna;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("300 tk");
            jTextField2.setText("5%");
            jTextField3.setText("315 tk");
            jTextField10.setText("315 tk only");
            
        }
        
        //Economy_Female_Adult_Khulna;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
         //Economy_Female_Child_Khulna;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("300 tk");
            jTextField2.setText("5%");
            jTextField3.setText("315 tk");
            jTextField10.setText("315 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Khulna;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Khulna;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Khulna;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Khulna;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Khulna"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Syllhet;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Standard_Male_Child_Syllhet;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("372.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Standard_Female_Adult_Syllhet;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
         //Standard_Female_Child_Syllhet;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("372.5 tk");
            jTextField10.setText("372.5 tk only");
            
        }
        
         //Economy_Male_Adult_Syllhet;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            jTextField1.setText("400 tk");
            jTextField2.setText("5%");
            jTextField3.setText("420 tk");
            jTextField10.setText("420 tk only");
            
        }
        
        //Economy_Male_Child_Syllhet;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("380 tk");
            jTextField2.setText("5%");
            jTextField3.setText("399 tk");
            jTextField10.setText("399 tk only");
            
        }
        
        //Economy_Female_Adult_Syllhet;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("400 tk");
            jTextField2.setText("5%");
            jTextField3.setText("420 tk");
            jTextField10.setText("420 tk only");
            
        }
        
         //Economy_Female_Child_Syllhet;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("380 tk");
            jTextField2.setText("5%");
            jTextField3.setText("399 tk");
            jTextField10.setText("399 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Syllhet;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Syllhet;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("560 tk");
            jTextField2.setText("5%");
            jTextField3.setText("588 tk");
            jTextField10.setText("588 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Syllhet;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Syllhet;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Syllhet"))){
            
            jTextField1.setText("560 tk");
            jTextField2.setText("5%");
            jTextField3.setText("588 tk");
            jTextField10.setText("588 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("796.48 tk");
            jTextField10.setText("796.48 tk only");
            
        }
        
        //Standard_Male_Child_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Standard_Female_Adult_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("796.48 tk");
            jTextField10.setText("796.48 tk only");
            
        }
        
         //Standard_Female_Child_Chittagong;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("759 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
         //Economy_Male_Adult_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("559 tk");
            jTextField2.setText("5%");
            jTextField3.setText("586.95 tk");
            jTextField10.setText("586.95 tk only");
            
        }
        
        //Economy_Male_Child_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Economy_Female_Adult_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("559 tk");
            jTextField2.setText("5%");
            jTextField3.setText("586.95 tk");
            jTextField10.setText("586.95 tk only");
            
        }
        
         //Economy_Female_Child_Chittagong;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("450 tk");
            jTextField2.setText("5%");
            jTextField3.setText("472.5 tk");
            jTextField10.setText("472.5 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("900 tk");
            jTextField2.setText("5%");
            jTextField3.setText("945 tk");
            jTextField10.setText("945 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("900 tk");
            jTextField2.setText("5%");
            jTextField3.setText("945 tk");
            jTextField10.setText("945 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Chittagong;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Chittagong"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("800 tk");
            jTextField2.setText("5%");
            jTextField3.setText("840 tk");
            jTextField10.setText("840 tk only");
            
        }
        
        //Standard_Male_Child_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("650 tk");
            jTextField2.setText("5%");
            jTextField3.setText("682.5 tk");
            jTextField10.setText("682.5 tk only");
            
        }
        
        //Standard_Female_Adult_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("800 tk");
            jTextField2.setText("5%");
            jTextField3.setText("840 tk");
            jTextField10.setText("840 tk only");
            
        }
        
         //Standard_Female_Child_Rajshahi;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("650 tk");
            jTextField2.setText("5%");
            jTextField3.setText("682.5 tk");
            jTextField10.setText("682.5 tk only");
            
        }
        
         //Economy_Male_Adult_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
        //Economy_Male_Child_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("367.5 tk only");
            
        }
        
        //Economy_Female_Adult_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("550 tk");
            jTextField2.setText("5%");
            jTextField3.setText("577.5 tk");
            jTextField10.setText("577.5 tk only");
            
        }
        
         //Economy_Female_Child_Rajshahi;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("350 tk");
            jTextField2.setText("5%");
            jTextField3.setText("367.5 tk");
            jTextField10.setText("367.5 tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Rajshahi;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rajshahi"))){
            
            jTextField1.setText("700 tk");
            jTextField2.setText("5%");
            jTextField3.setText("735 tk");
            jTextField10.setText("735 tk only");
            
        }
        
        //Total coast;
        //Standard_Male_Adult_Dinajpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
        //Standard_Male_Child_Dinajpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("850 tk");
            jTextField2.setText("5%");
            jTextField3.setText("892.5 tk");
            jTextField10.setText("892.5 tk only");
            
        }
        
        //Standard_Female_Adult_Dinajpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
         //Standard_Female_Child_Dinajpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("850 tk");
            jTextField2.setText("5%");
            jTextField3.setText("892.5 tk");
            jTextField10.setText("892.5 tk only");
            
        }
        
         //Economy_Male_Adult_Dinajpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("787.5 tk");
            jTextField10.setText("787.5 tk only");
            
        }
        
        //Economy_Male_Child_Dinajpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630 tk only");
            
        }
        
        //Economy_Female_Adult_Dinajpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("787.5tk");
            jTextField10.setText("787.5tk only");
            
        }
        
         //Economy_Female_Child_Dinajpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Dinajpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("1200 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1260 tk");
            jTextField10.setText("1260 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Dinajpur
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("1000 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1050 tk");
            jTextField10.setText("1050 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Dinajpur
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("1200 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1260 tk");
            jTextField10.setText("1260 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Dinajpur;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Dinajpur"))){
            
            jTextField1.setText("1000 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1050 tk");
            jTextField10.setText("1050 tk only");
            
        }
                //Total coast;
        //Standard_Male_Adult_Rangpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
        //Standard_Male_Child_Rangpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("850 tk");
            jTextField2.setText("5%");
            jTextField3.setText("892.5 tk");
            jTextField10.setText("892.5 tk only");
            
        }
        
        //Standard_Female_Adult_Rangpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("950 tk");
            jTextField2.setText("5%");
            jTextField3.setText("997.5 tk");
            jTextField10.setText("997.5 tk only");
            
        }
        
         //Standard_Female_Child_Rangpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("850 tk");
            jTextField2.setText("5%");
            jTextField3.setText("892.5 tk");
            jTextField10.setText("892.5 tk only");
            
        }
        
         //Economy_Male_Adult_Rangpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("787.5 tk");
            jTextField10.setText("787.5 tk only");
            
        }
        
        //Economy_Male_Child_Rangpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630 tk only");
            
        }
        
        //Economy_Female_Adult_Rangpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("750 tk");
            jTextField2.setText("5%");
            jTextField3.setText("787.5tk");
            jTextField10.setText("787.5tk only");
            
        }
        
         //Economy_Female_Child_Rangpur;
        else if((jRadioButton2.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("600 tk");
            jTextField2.setText("5%");
            jTextField3.setText("630 tk");
            jTextField10.setText("630tk only");
            
        }
        
        //Shovon Chair_Male_Adult_Rangpur;
        else if((jRadioButton1.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("1200 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1260 tk");
            jTextField10.setText("1260 tk only");
            
        }
        
        //Shovon Chair_Male_Child_Rangpur
        else if((jRadioButton3.isSelected()) && (jRadioButton5.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("1000 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1050 tk");
            jTextField10.setText("1050 tk only");
            
        }
        
        //Shovon Chair_Female_Adult_Rangpur
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton8.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("1200 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1260 tk");
            jTextField10.setText("1260 tk only");
            
        }
        
         //Shovon Chair_Female_Child_Rangpur;
        else if((jRadioButton3.isSelected()) && (jRadioButton4.isSelected()) && (jRadioButton7.isSelected()) && (jComboBox2.getSelectedItem().equals("Rangpur"))){
            
            jTextField1.setText("1000 tk");
            jTextField2.setText("5%");
            jTextField3.setText("1050 tk");
            jTextField10.setText("1050 tk only");
            
        }
        
        else {
            
            JOptionPane.showMessageDialog(null, "Please Select all Iteam");
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        //jLabel5.setText(null);
        //jLabel6.setText(null);
        jTextField6.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField4.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField7.setText(null);
        jTextField10.setText(null);
        jTextField5.setText(null);
        
        
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        
        jComboBox2.setSelectedItem("Select area");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(java.awt.Color.black);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTicketingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables



    
}

